# Generated by Django 5.1.3 on 2024-11-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waleed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(max_length=120)),
                ('emails', models.EmailField(max_length=100)),
                ('messages', models.TextField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
